package com.yueqian.mapper;

import com.yueqian.entity.HeadStock;
import java.util.List;

public interface HeadStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_stock
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_stock
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(HeadStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_stock
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    HeadStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_stock
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<HeadStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_stock
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(HeadStock record);
}