package com.yueqian.mapper;

import com.yueqian.entity.PayType;
import java.util.List;

public interface PayTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paytype
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paytype
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(PayType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paytype
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    PayType selectByPrimaryKey(Integer payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paytype
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<PayType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paytype
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(PayType record);
}