package com.yueqian.mapper;

import com.yueqian.entity.ProductCategory;
import org.apache.ibatis.annotations.Param;
;import java.util.List;


public interface ProductCategoryMapper {
    List<ProductCategory> selectOne();
    List<ProductCategory> selectTwo(@Param("id") Integer id);
    List<ProductCategory> selectThree(@Param("id") Integer id);



    /**
     * 分割线
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    ProductCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<ProductCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(ProductCategory record);
}