package com.yueqian.mapper;

import com.yueqian.entity.StoreSellDetail;
import java.util.List;

public interface StoreSellDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(StoreSellDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    StoreSellDetail selectByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<StoreSellDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(StoreSellDetail record);
}