package com.yueqian.mapper;

import com.yueqian.entity.StoreSell;
import java.util.List;

public interface StoreSellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(StoreSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    StoreSell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<StoreSell> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_sell
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(StoreSell record);
}