package com.yueqian.mapper;

import com.yueqian.entity.CollectionProduct;
import com.yueqian.entity.UserCollection;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserCollectionMapper {
    public List<CollectionProduct> selectByUserId(@Param("pageNo")Integer pageNo,@Param("pageSize")Integer pageSize,@Param("userId")Integer userId);//分页查询
    public int selectCount(@Param("userId")Integer userId);//查询总条数
    public int selectByUserIdProductId(@Param("productId")Integer productId,@Param("userId")Integer userId);//查询是否存在相应商品id人物id的收藏列
    public int adduserCollection(@Param("productId")Integer productId,@Param("userId")Integer userId,@Param("wudi")String shijian);//收藏商品
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(UserCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    UserCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<UserCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collection
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(UserCollection record);
}