package com.yueqian.mapper;

import com.yueqian.entity.DetailProduct;
import com.yueqian.entity.UserDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDetailMapper {

    public List<DetailProduct> selectByOrderId(@Param("id")Integer id);
    public List<DetailProduct> selectByOrder(@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    UserDetail selectByPrimaryKey(Integer detailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<UserDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(UserDetail record);
}