package com.yueqian.mapper;

import com.yueqian.entity.UserAddress;
import java.util.List;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    UserAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    List<UserAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    int updateByPrimaryKey(UserAddress record);
}