package com.yueqian.mapper;

import com.yueqian.entity.FootProduct;
import com.yueqian.entity.UserFootPrint;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserFootPrintMapper {
    public List<FootProduct> selectDay();//查询本天浏览记录
    public List<FootProduct> selectWeek();//查询一周内的浏览记录
    public int selectByProdictUser(@Param("productId")Integer productId,@Param("userId")Integer userId);//查询数据库中是否存在浏览的商品
    public int updateByDate(@Param("shijian")String shijian,@Param("productId")Integer productId,@Param("userId")Integer userId);//修改浏览过的商品的时间
    public int addUserFootPrint(@Param("shijian")String shijian,@Param("productId")Integer productId,@Param("userId")Integer userId);//添加浏览记录


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_footprint
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_footprint
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(UserFootPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_footprint
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    UserFootPrint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_footprint
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<UserFootPrint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_footprint
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(UserFootPrint record);
}