package com.yueqian.mapper;

import com.yueqian.entity.WebStoreUser;
import java.util.List;

public interface WebStoreUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webstore_user
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webstore_user
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int insert(WebStoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webstore_user
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    WebStoreUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webstore_user
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    List<WebStoreUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webstore_user
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    int updateByPrimaryKey(WebStoreUser record);
}