package com.yueqian.entity;

import java.util.Date;

public class Carousel {









    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.photo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.lastDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date lastdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.id
     *
     * @return the value of carousel.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.id
     *
     * @param id the value for carousel.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.photo
     *
     * @return the value of carousel.photo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.photo
     *
     * @param photo the value for carousel.photo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.lastDate
     *
     * @return the value of carousel.lastDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.lastDate
     *
     * @param lastdate the value for carousel.lastDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }
}