package com.yueqian.entity;

import java.util.Date;

public class Snapup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.startDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snapup.endDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.id
     *
     * @return the value of snapup.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.id
     *
     * @param id the value for snapup.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.productId
     *
     * @return the value of snapup.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.productId
     *
     * @param productid the value for snapup.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.price
     *
     * @return the value of snapup.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.price
     *
     * @param price the value for snapup.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.count
     *
     * @return the value of snapup.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.count
     *
     * @param count the value for snapup.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.startDate
     *
     * @return the value of snapup.startDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.startDate
     *
     * @param startdate the value for snapup.startDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snapup.endDate
     *
     * @return the value of snapup.endDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snapup.endDate
     *
     * @param enddate the value for snapup.endDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}