package com.yueqian.entity;

public class StoreSellDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell_detail.detailId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell_detail.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell_detail.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell_detail.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell_detail.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell_detail.detailId
     *
     * @return the value of store_sell_detail.detailId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell_detail.detailId
     *
     * @param detailid the value for store_sell_detail.detailId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell_detail.orderId
     *
     * @return the value of store_sell_detail.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell_detail.orderId
     *
     * @param orderid the value for store_sell_detail.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell_detail.productId
     *
     * @return the value of store_sell_detail.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell_detail.productId
     *
     * @param productid the value for store_sell_detail.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell_detail.count
     *
     * @return the value of store_sell_detail.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell_detail.count
     *
     * @param count the value for store_sell_detail.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell_detail.price
     *
     * @return the value of store_sell_detail.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell_detail.price
     *
     * @param price the value for store_sell_detail.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}