package com.yueqian.entity;

import java.util.Date;

public class StoreSell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.cashierId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer cashierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_sell.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.id
     *
     * @return the value of store_sell.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.id
     *
     * @param id the value for store_sell.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.branchId
     *
     * @return the value of store_sell.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.branchId
     *
     * @param branchid the value for store_sell.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setBranchid(Integer branchid) {
        this.branchid = branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.productId
     *
     * @return the value of store_sell.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.productId
     *
     * @param productid the value for store_sell.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.price
     *
     * @return the value of store_sell.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.price
     *
     * @param price the value for store_sell.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.payType
     *
     * @return the value of store_sell.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.payType
     *
     * @param paytype the value for store_sell.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.cashierId
     *
     * @return the value of store_sell.cashierId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getCashierid() {
        return cashierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.cashierId
     *
     * @param cashierid the value for store_sell.cashierId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setCashierid(Integer cashierid) {
        this.cashierid = cashierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_sell.date
     *
     * @return the value of store_sell.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_sell.date
     *
     * @param date the value for store_sell.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }
}