package com.yueqian.entity;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.branchNo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String branchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.userPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String userpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.branchNo
     *
     * @return the value of store.branchNo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getBranchno() {
        return branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.branchNo
     *
     * @param branchno the value for store.branchNo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setBranchno(String branchno) {
        this.branchno = branchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.userName
     *
     * @return the value of store.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.userName
     *
     * @param username the value for store.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.userPwd
     *
     * @return the value of store.userPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.userPwd
     *
     * @param userpwd the value for store.userPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }
}