package com.yueqian.entity;

public class StoreUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.type
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.name
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String passpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.id
     *
     * @return the value of store_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.id
     *
     * @param id the value for store_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.branchId
     *
     * @return the value of store_user.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.branchId
     *
     * @param branchid the value for store_user.branchId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setBranchid(Integer branchid) {
        this.branchid = branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.type
     *
     * @return the value of store_user.type
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.type
     *
     * @param type the value for store_user.type
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.name
     *
     * @return the value of store_user.name
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.name
     *
     * @param name the value for store_user.name
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_user.passPwd
     *
     * @return the value of store_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getPasspwd() {
        return passpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_user.passPwd
     *
     * @param passpwd the value for store_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPasspwd(String passpwd) {
        this.passpwd = passpwd;
    }
}