package com.yueqian.entity;

import java.util.Date;

public class UserCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.prodoctId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer prodoctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collection.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.id
     *
     * @return the value of user_collection.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.id
     *
     * @param id the value for user_collection.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.userId
     *
     * @return the value of user_collection.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.userId
     *
     * @param userid the value for user_collection.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.prodoctId
     *
     * @return the value of user_collection.prodoctId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProdoctid() {
        return prodoctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.prodoctId
     *
     * @param prodoctid the value for user_collection.prodoctId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProdoctid(Integer prodoctid) {
        this.prodoctid = prodoctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collection.date
     *
     * @return the value of user_collection.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collection.date
     *
     * @param date the value for user_collection.date
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }
}