package com.yueqian.entity;

public class UserShopCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopcar.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopcar.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopcar.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopcar.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopcar.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopcar.id
     *
     * @return the value of user_shopcar.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopcar.id
     *
     * @param id the value for user_shopcar.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopcar.userId
     *
     * @return the value of user_shopcar.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopcar.userId
     *
     * @param userid the value for user_shopcar.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopcar.productId
     *
     * @return the value of user_shopcar.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopcar.productId
     *
     * @param productid the value for user_shopcar.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopcar.price
     *
     * @return the value of user_shopcar.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopcar.price
     *
     * @param price the value for user_shopcar.price
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopcar.count
     *
     * @return the value of user_shopcar.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopcar.count
     *
     * @param count the value for user_shopcar.count
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}