package com.yueqian.entity;

import java.util.Date;

public class UserFootPrint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_footprint.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_footprint.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_footprint.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_footprint.data
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_footprint.id
     *
     * @return the value of user_footprint.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_footprint.id
     *
     * @param id the value for user_footprint.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_footprint.userId
     *
     * @return the value of user_footprint.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_footprint.userId
     *
     * @param userid the value for user_footprint.userId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_footprint.productId
     *
     * @return the value of user_footprint.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_footprint.productId
     *
     * @param productid the value for user_footprint.productId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_footprint.data
     *
     * @return the value of user_footprint.data
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_footprint.data
     *
     * @param data the value for user_footprint.data
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setData(Date data) {
        this.data = data;
    }
}