package com.yueqian.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.beans.factory.annotation.Value;

import java.util.Date;

public class UserOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer orderid;
    private Integer userId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.orderNo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String orderno;

    public String getOrderno() {
        return orderno;
    }

    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.orderStatus
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.address
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.logistics
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String logistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.orderLogisticsId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String orderlogisticsid;


    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    private Date orderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.deliveryDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Date deliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.priceCount
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Double pricecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.orderId
     *
     * @return the value of user_order.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.orderId
     *
     * @param orderid the value for user_order.orderId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.orderNo
     *
     * @return the value of user_order.orderNo
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.orderStatus
     *
     * @return the value of user_order.orderStatus
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.orderStatus
     *
     * @param orderstatus the value for user_order.orderStatus
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.address
     *
     * @return the value of user_order.address
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.address
     *
     * @param address the value for user_order.address
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.logistics
     *
     * @return the value of user_order.logistics
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getLogistics() {
        return logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.logistics
     *
     * @param logistics the value for user_order.logistics
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setLogistics(String logistics) {
        this.logistics = logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.orderLogisticsId
     *
     * @return the value of user_order.orderLogisticsId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getOrderlogisticsid() {
        return orderlogisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.orderLogisticsId
     *
     * @param orderlogisticsid the value for user_order.orderLogisticsId
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setOrderlogisticsid(String orderlogisticsid) {
        this.orderlogisticsid = orderlogisticsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.orderDate
     *
     * @return the value of user_order.orderDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.orderDate
     *
     * @param orderdate the value for user_order.orderDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.deliveryDate
     *
     * @return the value of user_order.deliveryDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Date getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.deliveryDate
     *
     * @param deliverydate the value for user_order.deliveryDate
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.payType
     *
     * @return the value of user_order.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.payType
     *
     * @param paytype the value for user_order.payType
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.priceCount
     *
     * @return the value of user_order.priceCount
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Double getPricecount() {
        return pricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.priceCount
     *
     * @param pricecount the value for user_order.priceCount
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPricecount(Double pricecount) {
        this.pricecount = pricecount;
    }
}