package com.yueqian.entity;

public class UserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.userId
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.defaults
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    private Integer defaults;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.userId
     *
     * @return the value of user_address.userId
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.userId
     *
     * @param userid the value for user_address.userId
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.defaults
     *
     * @return the value of user_address.defaults
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public Integer getDefaults() {
        return defaults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.defaults
     *
     * @param defaults the value for user_address.defaults
     *
     * @mbggenerated Mon Apr 16 08:51:46 CST 2018
     */
    public void setDefaults(Integer defaults) {
        this.defaults = defaults;
    }
}