package com.yueqian.entity;

public class WebStoreUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String passpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.phone
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.email
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.sex
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webstore_user.QQ
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    private String qq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.id
     *
     * @return the value of webstore_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.id
     *
     * @param id the value for webstore_user.id
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.userName
     *
     * @return the value of webstore_user.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.userName
     *
     * @param username the value for webstore_user.userName
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.passPwd
     *
     * @return the value of webstore_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getPasspwd() {
        return passpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.passPwd
     *
     * @param passpwd the value for webstore_user.passPwd
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPasspwd(String passpwd) {
        this.passpwd = passpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.phone
     *
     * @return the value of webstore_user.phone
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.phone
     *
     * @param phone the value for webstore_user.phone
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.email
     *
     * @return the value of webstore_user.email
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.email
     *
     * @param email the value for webstore_user.email
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.sex
     *
     * @return the value of webstore_user.sex
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.sex
     *
     * @param sex the value for webstore_user.sex
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webstore_user.QQ
     *
     * @return the value of webstore_user.QQ
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webstore_user.QQ
     *
     * @param qq the value for webstore_user.QQ
     *
     * @mbggenerated Mon Apr 16 08:35:34 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }
}